### ISSUE TITLE
mvn Building issue

### ISSUE THREAD

**Issue by earthat** [zishanfu/GeoSparkSim#5]
HI

I am trying to build but it throughs an error. I tried the with `mvn clean install ` but it generated error like four files format is unsupported. So I used

`sudo mvn com.coveo:fmt-maven-plugin:format`

then 

`mvn clean install `

It created the `target `directory inside the `module-main`. But it couldn't find the main class and the error is

`Error: Could not find or load main class com.zishanfu.geosparksim.GeoSparkSim`

Kindly guide to resolve it.

**Comment by zishanfu** [comment]
Try to use the stable branch by `git checkout stable` and do `mvn clean install`
